#!/bin/bash

sed -i 's/SonarQube/CodeScan/g' `git grep -l SonarQube`
sed -i 's/CodeScanNotification/SonarQubeNotification/g' `git grep -l CodeScanNotification`
sed -i 's/CodeScanUrls/SonarQubeUrls/g' `git grep -l CodeScanUrls`
sed -i 's/CodeScanServer/SonarQubeServer/g' `git grep -l CodeScanServer`
sed -i 's/logo\/sonarcloud/logo\/codescan/g' `git grep -l logo\/sonarcloud`
sed -i 's/CodeScan Server/SonarQube Server/g' `git grep -l 'CodeScan Server'`
sed -i 's/suggestedId = "SonarCloud"/suggestedId = "CodeScanCloud"/g' org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/server/wizard/ServerConnectionModel.java


if [ "$(git grep '<sonarlint.version>' | grep CODESCAN)" == "" ]; then
	git grep '<sonarlint.version>'
	echo "sonarlint.version must be convert to a CODESCAN version"
	exit 1
fi

git grep sonarcloud.io
if [ $? -eq 0 ]; then
	echo "sonarcloud.io must be converted"
	exit 1
fi

if [ ! -f org.sonarlint.eclipse.ui/icons/logo/codescan-16px.png ]; then
	echo "org.sonarlint.eclipse.ui/icons/logo/codescan-16px.png missing"
	exit
fi
if [ ! -f org.sonarlint.eclipse.ui/icons/logo/codescan-black-256px.png ]; then
	echo "org.sonarlint.eclipse.ui/icons/logo/codescan-black-256px.png missing"
	exit
fi

CURRENT_VERSION=`mvn help:evaluate -Dtycho.mode=maven -Dexpression="project.version" | grep -v '^\[\|Download\w\+\:'`
RELEASE_VERSION=`echo $CURRENT_VERSION | sed "s/-.*//g" | sed "s/.CODESCAN.*//g"`
NEW_VERSION="$RELEASE_VERSION.CODESCAN91"

echo "Replacing version $CURRENT_VERSION with $NEW_VERSION"
mvn org.eclipse.tycho:tycho-versions-plugin:0.26.0:set-version -Dtycho.mode=maven -DnewVersion=$NEW_VERSION -B -e

export PROJECT_VERSION=$NEW_VERSION

cp ../git-pmd/sonar-salesforce/sonar-salesforce-plugin/target/sonar-salesforce-plugin-*.jar org.sonarlint.eclipse.core/plugins/
rm org.sonarlint.eclipse.core/plugins/*sources*.jar


REPO_URL="file://`pwd`/org.sonarlint.eclipse.site/target/repository/"   
echo ""
echo ""
echo ""
echo mvn clean install -Dlicense.skip=true -Dmaven.test.skip=true -DfailIfNoTests=false \
	-Dsonarlint-eclipse.p2.url=$REPO_URL \
	-Dmaven.test.redirectTestOutputToFile=false \
	-Dtycho.disableP2Mirrors=true \
	-B -e -V 

echo ""
echo "On completion:, output will be ./org.sonarlint.eclipse.site/target/*.zip"


